//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEXCORE.Service.ServiceManager.MenuService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MenuService.IMenuService")]
    public interface IMenuService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/GetWMSMenuList", ReplyAction="http://tempuri.org/IMenuService/GetWMSMenuListResponse")]
        System.Collections.Generic.List<NEXCORE.Common.Data.Menu> GetWMSMenuList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/GetWMSDeptList", ReplyAction="http://tempuri.org/IMenuService/GetWMSDeptListResponse")]
        System.Collections.Generic.List<NEXCORE.Common.Data.Dept> GetWMSDeptList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/GetWMSMenuListByUser", ReplyAction="http://tempuri.org/IMenuService/GetWMSMenuListByUserResponse")]
        System.Collections.Generic.List<NEXCORE.Common.Data.Menu> GetWMSMenuListByUser(string userId, string sysid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/GetToolMenuList", ReplyAction="http://tempuri.org/IMenuService/GetToolMenuListResponse")]
        System.Collections.Generic.List<NEXCORE.Common.Data.Menu> GetToolMenuList(string authId, string sysid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/GetNavagatorMenu", ReplyAction="http://tempuri.org/IMenuService/GetNavagatorMenuResponse")]
        System.Collections.Generic.List<NEXCORE.Common.Data.Menu> GetNavagatorMenu(string authId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/GetAllMenuList", ReplyAction="http://tempuri.org/IMenuService/GetAllMenuListResponse")]
        System.Collections.Generic.List<NEXCORE.Common.Data.Menu> GetAllMenuList(string authId, string sysid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/GetMyMenuList", ReplyAction="http://tempuri.org/IMenuService/GetMyMenuListResponse")]
        System.Collections.Generic.List<NEXCORE.Common.Data.Menu> GetMyMenuList(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/AddMenu", ReplyAction="http://tempuri.org/IMenuService/AddMenuResponse")]
        void AddMenu(NEXCORE.Common.Data.Menu menu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/DeleteMenu", ReplyAction="http://tempuri.org/IMenuService/DeleteMenuResponse")]
        void DeleteMenu(NEXCORE.Common.Data.Menu menu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/UpdateMenu", ReplyAction="http://tempuri.org/IMenuService/UpdateMenuResponse")]
        void UpdateMenu(NEXCORE.Common.Data.Menu menu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/AddMyMenu", ReplyAction="http://tempuri.org/IMenuService/AddMyMenuResponse")]
        bool AddMyMenu(NEXCORE.Common.Data.Menu menu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/DeleteMyMenu", ReplyAction="http://tempuri.org/IMenuService/DeleteMyMenuResponse")]
        bool DeleteMyMenu(NEXCORE.Common.Data.Menu menu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/UpdateMyMenu", ReplyAction="http://tempuri.org/IMenuService/UpdateMyMenuResponse")]
        bool UpdateMyMenu(NEXCORE.Common.Data.Menu menu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/Reload", ReplyAction="http://tempuri.org/IMenuService/ReloadResponse")]
        void Reload();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMenuServiceChannel : NEXCORE.Service.ServiceManager.MenuService.IMenuService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MenuServiceClient : System.ServiceModel.ClientBase<NEXCORE.Service.ServiceManager.MenuService.IMenuService>, NEXCORE.Service.ServiceManager.MenuService.IMenuService {
        
        public MenuServiceClient() {
        }
        
        public MenuServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MenuServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MenuServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MenuServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<NEXCORE.Common.Data.Menu> GetWMSMenuList() {
            return base.Channel.GetWMSMenuList();
        }
        
        public System.Collections.Generic.List<NEXCORE.Common.Data.Dept> GetWMSDeptList() {
            return base.Channel.GetWMSDeptList();
        }
        
        public System.Collections.Generic.List<NEXCORE.Common.Data.Menu> GetWMSMenuListByUser(string userId, string sysid) {
            return base.Channel.GetWMSMenuListByUser(userId, sysid);
        }
        
        public System.Collections.Generic.List<NEXCORE.Common.Data.Menu> GetToolMenuList(string authId, string sysid) {
            return base.Channel.GetToolMenuList(authId, sysid);
        }
        
        public System.Collections.Generic.List<NEXCORE.Common.Data.Menu> GetNavagatorMenu(string authId) {
            return base.Channel.GetNavagatorMenu(authId);
        }
        
        public System.Collections.Generic.List<NEXCORE.Common.Data.Menu> GetAllMenuList(string authId, string sysid) {
            return base.Channel.GetAllMenuList(authId, sysid);
        }
        
        public System.Collections.Generic.List<NEXCORE.Common.Data.Menu> GetMyMenuList(string userId) {
            return base.Channel.GetMyMenuList(userId);
        }
        
        public void AddMenu(NEXCORE.Common.Data.Menu menu) {
            base.Channel.AddMenu(menu);
        }
        
        public void DeleteMenu(NEXCORE.Common.Data.Menu menu) {
            base.Channel.DeleteMenu(menu);
        }
        
        public void UpdateMenu(NEXCORE.Common.Data.Menu menu) {
            base.Channel.UpdateMenu(menu);
        }
        
        public bool AddMyMenu(NEXCORE.Common.Data.Menu menu) {
            return base.Channel.AddMyMenu(menu);
        }
        
        public bool DeleteMyMenu(NEXCORE.Common.Data.Menu menu) {
            return base.Channel.DeleteMyMenu(menu);
        }
        
        public bool UpdateMyMenu(NEXCORE.Common.Data.Menu menu) {
            return base.Channel.UpdateMyMenu(menu);
        }
        
        public void Reload() {
            base.Channel.Reload();
        }
    }
}
