//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.1
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEXCORE.Service.ServiceManager.UserService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserService.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DoWork", ReplyAction="http://tempuri.org/IUserService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Login", ReplyAction="http://tempuri.org/IUserService/LoginResponse")]
        NEXCORE.Interfaces.LOGIN_RESULT_CODE Login(string userId, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUser", ReplyAction="http://tempuri.org/IUserService/GetUserResponse")]
        NEXCORE.Common.Data.User GetUser(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUsers", ReplyAction="http://tempuri.org/IUserService/GetUsersResponse")]
        NEXCORE.Common.Data.User[] GetUsers(string usernm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ModifyLockUser", ReplyAction="http://tempuri.org/IUserService/ModifyLockUserResponse")]
        bool ModifyLockUser(string userId, string lockyn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ErrorLog", ReplyAction="http://tempuri.org/IUserService/ErrorLogResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.User))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.User[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.DBNull))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Interfaces.LOGIN_RESULT_CODE))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
        bool ErrorLog(NEXCORE.Common.Data.NEXCOREData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/LoginHistory", ReplyAction="http://tempuri.org/IUserService/LoginHistoryResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.User))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.User[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.DBNull))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Interfaces.LOGIN_RESULT_CODE))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
        bool LoginHistory(NEXCORE.Common.Data.NEXCOREData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/PgmHistory", ReplyAction="http://tempuri.org/IUserService/PgmHistoryResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.User))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.User[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.DBNull))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Interfaces.LOGIN_RESULT_CODE))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
        bool PgmHistory(NEXCORE.Common.Data.NEXCOREData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ButtonHistory", ReplyAction="http://tempuri.org/IUserService/ButtonHistoryResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.User))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.User[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.DBNull))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Interfaces.LOGIN_RESULT_CODE))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
        bool ButtonHistory(NEXCORE.Common.Data.NEXCOREData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ChangePassword", ReplyAction="http://tempuri.org/IUserService/ChangePasswordResponse")]
        bool ChangePassword(string userId, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddUser", ReplyAction="http://tempuri.org/IUserService/AddUserResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.User))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.User[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.DBNull))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Interfaces.LOGIN_RESULT_CODE))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
        bool AddUser(NEXCORE.Common.Data.NEXCOREData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateUser", ReplyAction="http://tempuri.org/IUserService/UpdateUserResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.User))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.User[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.DBNull))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Interfaces.LOGIN_RESULT_CODE))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
        bool UpdateUser(NEXCORE.Common.Data.NEXCOREData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/EtcUpdateUser", ReplyAction="http://tempuri.org/IUserService/EtcUpdateUserResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.User))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.User[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.DBNull))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Interfaces.LOGIN_RESULT_CODE))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
        bool EtcUpdateUser(NEXCORE.Common.Data.NEXCOREData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteUser", ReplyAction="http://tempuri.org/IUserService/DeleteUserResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.User))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.User[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.DBNull))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Interfaces.LOGIN_RESULT_CODE))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
        bool DeleteUser(NEXCORE.Common.Data.NEXCOREData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Reload", ReplyAction="http://tempuri.org/IUserService/ReloadResponse")]
        void Reload();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : NEXCORE.Service.ServiceManager.UserService.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<NEXCORE.Service.ServiceManager.UserService.IUserService>, NEXCORE.Service.ServiceManager.UserService.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public NEXCORE.Interfaces.LOGIN_RESULT_CODE Login(string userId, string password) {
            return base.Channel.Login(userId, password);
        }
        
        public NEXCORE.Common.Data.User GetUser(string userId) {
            return base.Channel.GetUser(userId);
        }
        
        public NEXCORE.Common.Data.User[] GetUsers(string usernm) {
            return base.Channel.GetUsers(usernm);
        }
        
        public bool ModifyLockUser(string userId, string lockyn) {
            return base.Channel.ModifyLockUser(userId, lockyn);
        }
        
        public bool ErrorLog(NEXCORE.Common.Data.NEXCOREData data) {
            return base.Channel.ErrorLog(data);
        }
        
        public bool LoginHistory(NEXCORE.Common.Data.NEXCOREData data) {
            return base.Channel.LoginHistory(data);
        }
        
        public bool PgmHistory(NEXCORE.Common.Data.NEXCOREData data) {
            return base.Channel.PgmHistory(data);
        }
        
        public bool ButtonHistory(NEXCORE.Common.Data.NEXCOREData data) {
            return base.Channel.ButtonHistory(data);
        }
        
        public bool ChangePassword(string userId, string password) {
            return base.Channel.ChangePassword(userId, password);
        }
        
        public bool AddUser(NEXCORE.Common.Data.NEXCOREData data) {
            return base.Channel.AddUser(data);
        }
        
        public bool UpdateUser(NEXCORE.Common.Data.NEXCOREData data) {
            return base.Channel.UpdateUser(data);
        }
        
        public bool EtcUpdateUser(NEXCORE.Common.Data.NEXCOREData data) {
            return base.Channel.EtcUpdateUser(data);
        }
        
        public bool DeleteUser(NEXCORE.Common.Data.NEXCOREData data) {
            return base.Channel.DeleteUser(data);
        }
        
        public void Reload() {
            base.Channel.Reload();
        }
    }
}
