//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.296
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEXCORE.Service.ServiceManager.AuthorityService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthorityService.IAuthorityService")]
    public interface IAuthorityService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorityService/DoWork", ReplyAction="http://tempuri.org/IAuthorityService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorityService/GetAuthorityList", ReplyAction="http://tempuri.org/IAuthorityService/GetAuthorityListResponse")]
        System.Collections.Generic.List<NEXCORE.Common.Data.Authority> GetAuthorityList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorityService/GetAuthorityPgmList", ReplyAction="http://tempuri.org/IAuthorityService/GetAuthorityPgmListResponse")]
        System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityPgm> GetAuthorityPgmList(string authId, string all);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorityService/GetAuthorityUserList", ReplyAction="http://tempuri.org/IAuthorityService/GetAuthorityUserListResponse")]
        System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityUser> GetAuthorityUserList(string authId, string usernm, string deptnm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorityService/GetAuthorityPgm", ReplyAction="http://tempuri.org/IAuthorityService/GetAuthorityPgmResponse")]
        System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityPgm> GetAuthorityPgm(string authId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorityService/GetUserAuthorityList", ReplyAction="http://tempuri.org/IAuthorityService/GetUserAuthorityListResponse")]
        System.Collections.Generic.List<NEXCORE.Common.Data.UserAuthority> GetUserAuthorityList(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorityService/GetAuthorityListByCondition", ReplyAction="http://tempuri.org/IAuthorityService/GetAuthorityListByConditionResponse")]
        System.Collections.Generic.List<NEXCORE.Common.Data.Authority> GetAuthorityListByCondition(string authId, string authName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorityService/GetAuthorityButtonList", ReplyAction="http://tempuri.org/IAuthorityService/GetAuthorityButtonListResponse")]
        System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityButton> GetAuthorityButtonList(string authId, string pgmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorityService/GetUserButtonList", ReplyAction="http://tempuri.org/IAuthorityService/GetUserButtonListResponse")]
        System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityButton> GetUserButtonList(string userId, string pgmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorityService/GetLogList", ReplyAction="http://tempuri.org/IAuthorityService/GetLogListResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.DBNull))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.Authority>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.Authority))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityPgm>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.AuthorityPgm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityUser>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.AuthorityUser))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.UserAuthority>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.UserAuthority))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityButton>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.AuthorityButton))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.ButtonAuthority>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.ButtonAuthority))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.ManagedButton))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.ManagedButton>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
        NEXCORE.Common.Data.NEXCOREData GetLogList(string Type, string start, string end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorityService/GetAuthority", ReplyAction="http://tempuri.org/IAuthorityService/GetAuthorityResponse")]
        NEXCORE.Common.Data.Authority GetAuthority(string authId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorityService/DeleteAuthority", ReplyAction="http://tempuri.org/IAuthorityService/DeleteAuthorityResponse")]
        bool DeleteAuthority(string authId, bool deleteChildAuth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorityService/ModifyAuthority", ReplyAction="http://tempuri.org/IAuthorityService/ModifyAuthorityResponse")]
        bool ModifyAuthority(NEXCORE.Common.Data.Authority authority);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorityService/AddUserAuth", ReplyAction="http://tempuri.org/IAuthorityService/AddUserAuthResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.DBNull))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.Authority>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.Authority))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityPgm>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.AuthorityPgm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityUser>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.AuthorityUser))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.UserAuthority>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.UserAuthority))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityButton>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.AuthorityButton))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.ButtonAuthority>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.ButtonAuthority))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.ManagedButton))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.ManagedButton>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
        bool AddUserAuth(NEXCORE.Common.Data.NEXCOREData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorityService/AddAuthPgm", ReplyAction="http://tempuri.org/IAuthorityService/AddAuthPgmResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.DBNull))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.Authority>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.Authority))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityPgm>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.AuthorityPgm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityUser>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.AuthorityUser))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.UserAuthority>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.UserAuthority))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityButton>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.AuthorityButton))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.ButtonAuthority>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.ButtonAuthority))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.ManagedButton))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.ManagedButton>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
        bool AddAuthPgm(NEXCORE.Common.Data.NEXCOREData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorityService/AddAuthUser", ReplyAction="http://tempuri.org/IAuthorityService/AddAuthUserResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.DBNull))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.Authority>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.Authority))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityPgm>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.AuthorityPgm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityUser>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.AuthorityUser))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.UserAuthority>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.UserAuthority))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityButton>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.AuthorityButton))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.ButtonAuthority>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.ButtonAuthority))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.ManagedButton))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.ManagedButton>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
        bool AddAuthUser(NEXCORE.Common.Data.NEXCOREData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorityService/AddAuth", ReplyAction="http://tempuri.org/IAuthorityService/AddAuthResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.DBNull))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.Authority>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.Authority))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityPgm>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.AuthorityPgm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityUser>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.AuthorityUser))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.UserAuthority>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.UserAuthority))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityButton>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.AuthorityButton))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.ButtonAuthority>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.ButtonAuthority))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.ManagedButton))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.ManagedButton>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
        bool AddAuth(NEXCORE.Common.Data.NEXCOREData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorityService/UpdateAuth", ReplyAction="http://tempuri.org/IAuthorityService/UpdateAuthResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.DBNull))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.Authority>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.Authority))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityPgm>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.AuthorityPgm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityUser>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.AuthorityUser))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.UserAuthority>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.UserAuthority))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityButton>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.AuthorityButton))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.ButtonAuthority>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.ButtonAuthority))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.ManagedButton))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.ManagedButton>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
        bool UpdateAuth(NEXCORE.Common.Data.NEXCOREData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorityService/DeleteAuth", ReplyAction="http://tempuri.org/IAuthorityService/DeleteAuthResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.DBNull))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.Authority>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.Authority))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityPgm>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.AuthorityPgm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityUser>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.AuthorityUser))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.UserAuthority>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.UserAuthority))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityButton>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.AuthorityButton))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.ButtonAuthority>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.ButtonAuthority))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.ManagedButton))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.ManagedButton>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
        bool DeleteAuth(NEXCORE.Common.Data.NEXCOREData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorityService/DupCheck", ReplyAction="http://tempuri.org/IAuthorityService/DupCheckResponse")]
        int DupCheck(string TableName, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorityService/GetButtonAuthority", ReplyAction="http://tempuri.org/IAuthorityService/GetButtonAuthorityResponse")]
        System.Collections.Generic.List<NEXCORE.Common.Data.ButtonAuthority> GetButtonAuthority(string userId, string pgmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorityService/GetButton", ReplyAction="http://tempuri.org/IAuthorityService/GetButtonResponse")]
        NEXCORE.Common.Data.ManagedButton GetButton(string btnId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorityService/GetButtonList", ReplyAction="http://tempuri.org/IAuthorityService/GetButtonListResponse")]
        System.Collections.Generic.List<NEXCORE.Common.Data.ManagedButton> GetButtonList(string pgmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorityService/GetButtonListAll", ReplyAction="http://tempuri.org/IAuthorityService/GetButtonListAllResponse")]
        System.Collections.Generic.List<NEXCORE.Common.Data.ManagedButton> GetButtonListAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorityService/AddButton", ReplyAction="http://tempuri.org/IAuthorityService/AddButtonResponse")]
        bool AddButton(NEXCORE.Common.Data.ManagedButton button);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorityService/UpdateButton", ReplyAction="http://tempuri.org/IAuthorityService/UpdateButtonResponse")]
        bool UpdateButton(NEXCORE.Common.Data.ManagedButton button);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorityService/DeleteButton", ReplyAction="http://tempuri.org/IAuthorityService/DeleteButtonResponse")]
        bool DeleteButton(NEXCORE.Common.Data.ManagedButton button);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorityService/AddAuthButton", ReplyAction="http://tempuri.org/IAuthorityService/AddAuthButtonResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.DBNull))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.Authority>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.Authority))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityPgm>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.AuthorityPgm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityUser>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.AuthorityUser))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.UserAuthority>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.UserAuthority))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityButton>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.AuthorityButton))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.ButtonAuthority>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.ButtonAuthority))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.ManagedButton))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.ManagedButton>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
        bool AddAuthButton(NEXCORE.Common.Data.NEXCOREData data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthorityServiceChannel : NEXCORE.Service.ServiceManager.AuthorityService.IAuthorityService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthorityServiceClient : System.ServiceModel.ClientBase<NEXCORE.Service.ServiceManager.AuthorityService.IAuthorityService>, NEXCORE.Service.ServiceManager.AuthorityService.IAuthorityService {
        
        public AuthorityServiceClient() {
        }
        
        public AuthorityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthorityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthorityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthorityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Collections.Generic.List<NEXCORE.Common.Data.Authority> GetAuthorityList() {
            return base.Channel.GetAuthorityList();
        }
        
        public System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityPgm> GetAuthorityPgmList(string authId, string all) {
            return base.Channel.GetAuthorityPgmList(authId, all);
        }
        
        public System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityUser> GetAuthorityUserList(string authId, string usernm, string deptnm) {
            return base.Channel.GetAuthorityUserList(authId, usernm, deptnm);
        }
        
        public System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityPgm> GetAuthorityPgm(string authId) {
            return base.Channel.GetAuthorityPgm(authId);
        }
        
        public System.Collections.Generic.List<NEXCORE.Common.Data.UserAuthority> GetUserAuthorityList(string userId) {
            return base.Channel.GetUserAuthorityList(userId);
        }
        
        public System.Collections.Generic.List<NEXCORE.Common.Data.Authority> GetAuthorityListByCondition(string authId, string authName) {
            return base.Channel.GetAuthorityListByCondition(authId, authName);
        }
        
        public System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityButton> GetAuthorityButtonList(string authId, string pgmId) {
            return base.Channel.GetAuthorityButtonList(authId, pgmId);
        }
        
        public System.Collections.Generic.List<NEXCORE.Common.Data.AuthorityButton> GetUserButtonList(string userId, string pgmId) {
            return base.Channel.GetUserButtonList(userId, pgmId);
        }
        
        public NEXCORE.Common.Data.NEXCOREData GetLogList(string Type, string start, string end) {
            return base.Channel.GetLogList(Type, start, end);
        }
        
        public NEXCORE.Common.Data.Authority GetAuthority(string authId) {
            return base.Channel.GetAuthority(authId);
        }
        
        public bool DeleteAuthority(string authId, bool deleteChildAuth) {
            return base.Channel.DeleteAuthority(authId, deleteChildAuth);
        }
        
        public bool ModifyAuthority(NEXCORE.Common.Data.Authority authority) {
            return base.Channel.ModifyAuthority(authority);
        }
        
        public bool AddUserAuth(NEXCORE.Common.Data.NEXCOREData data) {
            return base.Channel.AddUserAuth(data);
        }
        
        public bool AddAuthPgm(NEXCORE.Common.Data.NEXCOREData data) {
            return base.Channel.AddAuthPgm(data);
        }
        
        public bool AddAuthUser(NEXCORE.Common.Data.NEXCOREData data) {
            return base.Channel.AddAuthUser(data);
        }
        
        public bool AddAuth(NEXCORE.Common.Data.NEXCOREData data) {
            return base.Channel.AddAuth(data);
        }
        
        public bool UpdateAuth(NEXCORE.Common.Data.NEXCOREData data) {
            return base.Channel.UpdateAuth(data);
        }
        
        public bool DeleteAuth(NEXCORE.Common.Data.NEXCOREData data) {
            return base.Channel.DeleteAuth(data);
        }
        
        public int DupCheck(string TableName, string key) {
            return base.Channel.DupCheck(TableName, key);
        }
        
        public System.Collections.Generic.List<NEXCORE.Common.Data.ButtonAuthority> GetButtonAuthority(string userId, string pgmId) {
            return base.Channel.GetButtonAuthority(userId, pgmId);
        }
        
        public NEXCORE.Common.Data.ManagedButton GetButton(string btnId) {
            return base.Channel.GetButton(btnId);
        }
        
        public System.Collections.Generic.List<NEXCORE.Common.Data.ManagedButton> GetButtonList(string pgmId) {
            return base.Channel.GetButtonList(pgmId);
        }
        
        public System.Collections.Generic.List<NEXCORE.Common.Data.ManagedButton> GetButtonListAll() {
            return base.Channel.GetButtonListAll();
        }
        
        public bool AddButton(NEXCORE.Common.Data.ManagedButton button) {
            return base.Channel.AddButton(button);
        }
        
        public bool UpdateButton(NEXCORE.Common.Data.ManagedButton button) {
            return base.Channel.UpdateButton(button);
        }
        
        public bool DeleteButton(NEXCORE.Common.Data.ManagedButton button) {
            return base.Channel.DeleteButton(button);
        }
        
        public bool AddAuthButton(NEXCORE.Common.Data.NEXCOREData data) {
            return base.Channel.AddAuthButton(data);
        }
    }
}
