//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.296
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEXCORE.Service.ServiceManager.CodeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CodeService.ICodeService")]
    public interface ICodeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeService/DoWork", ReplyAction="http://tempuri.org/ICodeService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeService/GetCode", ReplyAction="http://tempuri.org/ICodeService/GetCodeResponse")]
        NEXCORE.Common.Data.Code GetCode(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeService/GetCodes", ReplyAction="http://tempuri.org/ICodeService/GetCodesResponse")]
        System.Collections.Generic.List<NEXCORE.Common.Data.Code> GetCodes(string parentCodeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeService/GetHelpWindow", ReplyAction="http://tempuri.org/ICodeService/GetHelpWindowResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.DBNull))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.Code))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.Code>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<string>))]
        NEXCORE.Common.Data.NEXCOREData GetHelpWindow(NEXCORE.Common.Data.NEXCOREData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeService/GetHelpProduct", ReplyAction="http://tempuri.org/ICodeService/GetHelpProductResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.DBNull))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NEXCORE.Common.Data.Code))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<NEXCORE.Common.Data.Code>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<string>))]
        NEXCORE.Common.Data.NEXCOREData GetHelpProduct(NEXCORE.Common.Data.NEXCOREData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeService/GetCodesByAttribute", ReplyAction="http://tempuri.org/ICodeService/GetCodesByAttributeResponse")]
        System.Collections.Generic.List<NEXCORE.Common.Data.Code> GetCodesByAttribute(string parentCodeId, System.Collections.Generic.List<string> codeAttributes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeService/Reload", ReplyAction="http://tempuri.org/ICodeService/ReloadResponse")]
        void Reload();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICodeServiceChannel : NEXCORE.Service.ServiceManager.CodeService.ICodeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CodeServiceClient : System.ServiceModel.ClientBase<NEXCORE.Service.ServiceManager.CodeService.ICodeService>, NEXCORE.Service.ServiceManager.CodeService.ICodeService {
        
        public CodeServiceClient() {
        }
        
        public CodeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CodeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public NEXCORE.Common.Data.Code GetCode(string id) {
            return base.Channel.GetCode(id);
        }
        
        public System.Collections.Generic.List<NEXCORE.Common.Data.Code> GetCodes(string parentCodeId) {
            return base.Channel.GetCodes(parentCodeId);
        }
        
        public NEXCORE.Common.Data.NEXCOREData GetHelpWindow(NEXCORE.Common.Data.NEXCOREData data) {
            return base.Channel.GetHelpWindow(data);
        }
        
        public NEXCORE.Common.Data.NEXCOREData GetHelpProduct(NEXCORE.Common.Data.NEXCOREData data) {
            return base.Channel.GetHelpProduct(data);
        }
        
        public System.Collections.Generic.List<NEXCORE.Common.Data.Code> GetCodesByAttribute(string parentCodeId, System.Collections.Generic.List<string> codeAttributes) {
            return base.Channel.GetCodesByAttribute(parentCodeId, codeAttributes);
        }
        
        public void Reload() {
            base.Channel.Reload();
        }
    }
}
